language: node_js
node_js: 13
env:
  - CODECOV_TOKEN="138fa62b-8ba8-44c4-a175-f4efa1870149"
install:
  - npm ci
script:
  - npm run test
after-script:
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
  - bash <(curl -s https://codecov.io/bash) -f .nyc_output/out.json
